### ISSUE TITLE
about using 3d nifti file format!

### ISSUE THREAD

**Issue by jhkang0526** [MECLabTUDA/M3d-Cam#2]
Dear @MECLabTUDA ,

Thanks for your code! 

i have a question about 3d data classification.

Does this network not work for classification using 3d nitfi files? 
When I used this, I checked that only feature map(ex. 2*2*2size.) is saved.

Can you please help me out with this issue?

Best,
kang

p.s. I proceeded with <Medcam_classification_demo.ipynb> as a reference.

**Comment by Karol-G** [comment]
Hi Kang,

M3d-Cam is able to handle 3D nifti data.
Can you provide a bit more detail about your problem please.
Which network are you using? If it is open source please send me the link otherwise maybe describe the architecture.
What is the shape of your data?

Please also paste a snipped of your code using M3d-Cam and the stack trace of the thrown error.

Best
Karol

**Comment by Karol-G** [comment]
Closed due to inactivity.
